### ISSUE TITLE
Interpretation of bit values not working correctly

### ISSUE THREAD

**Issue by greendog99** [linuxkidd/rvc-monitor-py#1]
The yaml for ATS_AC_STATUS_1 contains this segment which should return a single bit (bit #7, data type bit1):

```
name: ATS_AC_STATUS_1
parameters:
    - byte: 0
      bit: 7
      name: leg
      type: bit1
      values:
        0: 1
        1: 2
```

The `rvc2mqtt.py` script returns the following json: `{ "leg": "10000110" }` which is the entire byte converted to binary. Ruby version returns { "leg": "0", "leg_definition": 1 }`.

Going to take a look at this to see what I can figure out:

https://github.com/linuxkidd/rvc-monitor-py/blob/d0486a662f47ad984b3d70999eadf535899ba073/usr/bin/rvc2mqtt.py#L141-L147
